/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'hero-section': HeroSection;
    'about-section': AboutSection;
    'why-choose-section': WhyChooseSection;
    'contact-section': ContactSection;
    'portfolio-section': PortfolioSection;
    features: Feature;
    testimonials: Testimonial;
    'pricing-plans': PricingPlan;
    faq: Faq;
    partners: Partner;
    'platform-availability': PlatformAvailability;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
    'why-choose-section': WhyChooseSectionSelect<false> | WhyChooseSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
    'portfolio-section': PortfolioSectionSelect<false> | PortfolioSectionSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'platform-availability': PlatformAvailabilitySelect<false> | PlatformAvailabilitySelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Hero section content for the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  heroImage?: (number | null) | Media;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * About section content with carousel slides
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slides?:
    | {
        title: string;
        description: string;
        image: number | Media;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  rotatingImages?:
    | {
        image: number | Media;
        alt?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  carouselConfig?: {
    autoSlide?: boolean | null;
    slideInterval?: number | null;
    pauseOnHover?: boolean | null;
  };
  isActive?: boolean | null;
  /**
   * Order of appearance in landing page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Why choose us section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-choose-section".
 */
export interface WhyChooseSection {
  id: number;
  title: string;
  subtitle?: string | null;
  points?:
    | {
        title: string;
        description: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sideImage?: (number | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact Us section content for landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formConfig?: {
    nameLabel?: string | null;
    whatsappLabel?: string | null;
    institutionLabel?: string | null;
    messageLabel?: string | null;
    submitButtonText?: string | null;
    successMessage?: string | null;
  };
  contactInfo?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    workingHours?: string | null;
    /**
     * Format: +62812345678 (dengan kode negara)
     */
    whatsappNumber?: string | null;
  };
  isActive?: boolean | null;
  /**
   * Order of appearance in landing page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Portfolio/Partners section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-section".
 */
export interface PortfolioSection {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'university' | 'school' | 'corporate' | 'government' | 'training';
  logos?:
    | {
        logo: number | Media;
        name: string;
        /**
         * Optional: Link to institution website
         */
        url?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  /**
   * Order of appearance in landing page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  title: string;
  description: string;
  icon?: (number | null) | Media;
  image?: (number | null) | Media;
  position: 'left' | 'right';
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  isActive?: boolean | null;
  /**
   * Order of appearance on the page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  position: string;
  school?: string | null;
  content: string;
  /**
   * Rating from 1 to 5 stars
   */
  rating?: number | null;
  avatar?: (number | null) | Media;
  testimonialTitle?: string | null;
  isActive?: boolean | null;
  /**
   * Order of appearance in testimonial slider
   */
  order?: number | null;
  /**
   * Show this testimonial prominently
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  price: number;
  period: 'month' | 'year' | 'once';
  currency: 'usd' | 'idr' | 'eur';
  description: string;
  features: {
    feature: string;
    /**
     * Is this feature included in the plan?
     */
    isIncluded?: boolean | null;
    id?: string | null;
  }[];
  ctaText: string;
  ctaLink: string;
  /**
   * Mark this plan as most popular (highlight)
   */
  isPopular?: boolean | null;
  badge?: string | null;
  isActive?: boolean | null;
  /**
   * Order of appearance on pricing page
   */
  order?: number | null;
  limitations?:
    | {
        limitation: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'features' | 'technical' | 'pricing' | 'account' | 'support';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  /**
   * Order of appearance in FAQ section
   */
  order?: number | null;
  /**
   * Show this FAQ prominently
   */
  isFeatured?: boolean | null;
  /**
   * How many users found this helpful
   */
  helpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  type: 'school' | 'university' | 'company' | 'government' | 'ngo';
  description?: string | null;
  website?: string | null;
  location?: string | null;
  partnershipDate?: string | null;
  studentCount?: number | null;
  isActive?: boolean | null;
  /**
   * Order of appearance in partners section
   */
  order?: number | null;
  /**
   * Show this partner prominently
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform availability section with 3 platform showcase
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-availability".
 */
export interface PlatformAvailability {
  id: number;
  sectionTitle: string;
  subtitle?: string | null;
  platforms?:
    | {
        name: string;
        /**
         * Used for platform selection (e.g., "Android", "Website", "IOS")
         */
        slug: string;
        mockupImage?: (number | null) | Media;
        description?: string | null;
        /**
         * Only one platform should be marked as default
         */
        isDefault?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  infoBanner?: {
    text?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    /**
     * CSS color value (hex, rgb, etc.)
     */
    backgroundColor?: string | null;
  };
  isActive?: boolean | null;
  /**
   * Order of appearance in landing page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-section';
        value: number | HeroSection;
      } | null)
    | ({
        relationTo: 'about-section';
        value: number | AboutSection;
      } | null)
    | ({
        relationTo: 'why-choose-section';
        value: number | WhyChooseSection;
      } | null)
    | ({
        relationTo: 'contact-section';
        value: number | ContactSection;
      } | null)
    | ({
        relationTo: 'portfolio-section';
        value: number | PortfolioSection;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'platform-availability';
        value: number | PlatformAvailability;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  ctaText?: T;
  ctaLink?: T;
  heroImage?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  slides?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        order?: T;
        id?: T;
      };
  rotatingImages?:
    | T
    | {
        image?: T;
        alt?: T;
        order?: T;
        id?: T;
      };
  carouselConfig?:
    | T
    | {
        autoSlide?: T;
        slideInterval?: T;
        pauseOnHover?: T;
      };
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-choose-section_select".
 */
export interface WhyChooseSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  points?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  sideImage?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  formConfig?:
    | T
    | {
        nameLabel?: T;
        whatsappLabel?: T;
        institutionLabel?: T;
        messageLabel?: T;
        submitButtonText?: T;
        successMessage?: T;
      };
  contactInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        workingHours?: T;
        whatsappNumber?: T;
      };
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-section_select".
 */
export interface PortfolioSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  category?: T;
  logos?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        order?: T;
        id?: T;
      };
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  image?: T;
  position?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  school?: T;
  content?: T;
  rating?: T;
  avatar?: T;
  testimonialTitle?: T;
  isActive?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  period?: T;
  currency?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        isIncluded?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  isPopular?: T;
  badge?: T;
  isActive?: T;
  order?: T;
  limitations?:
    | T
    | {
        limitation?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  isActive?: T;
  order?: T;
  isFeatured?: T;
  helpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  type?: T;
  description?: T;
  website?: T;
  location?: T;
  partnershipDate?: T;
  studentCount?: T;
  isActive?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-availability_select".
 */
export interface PlatformAvailabilitySelect<T extends boolean = true> {
  sectionTitle?: T;
  subtitle?: T;
  platforms?:
    | T
    | {
        name?: T;
        slug?: T;
        mockupImage?: T;
        description?: T;
        isDefault?: T;
        order?: T;
        id?: T;
      };
  infoBanner?:
    | T
    | {
        text?: T;
        buttonLabel?: T;
        buttonLink?: T;
        backgroundColor?: T;
      };
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}